# Generated by Django 5.0.3 on 2024-03-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternalStakeholder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("sub_county", models.CharField(max_length=100)),
                ("ward", models.CharField(max_length=100)),
                ("member_of_group", models.BooleanField()),
                ("group_name", models.CharField(blank=True, max_length=255)),
                ("membership_position", models.CharField(max_length=100)),
                ("group_registered", models.BooleanField()),
                ("group_operational_years", models.CharField(max_length=20)),
            ],
        ),
    ]
