# Generated by Django 3.2 on 2024-03-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msme_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msmequestionnaire',
            name='email',
        ),
    ]
