# Generated by Django 3.2 on 2024-03-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msme_app', '0002_remove_msmequestionnaire_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='msmequestionnaire',
            name='cboreg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='msmequestionnaire',
            name='disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='msmequestionnaire',
            name='email',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='msmequestionnaire',
            name='groupname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='msmequestionnaire',
            name='groupoperationalyears',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='msmequestionnaire',
            name='groupreg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='msmequestionnaire',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
