# Generated by Django 3.2 on 2024-04-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msme_app', '0003_auto_20240327_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msmequestionnaire',
            name='groupreg',
        ),
        migrations.AlterField(
            model_name='msmequestionnaire',
            name='cboreg',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='msmequestionnaire',
            name='disability',
            field=models.CharField(max_length=100),
        ),
    ]
