# Generated by Django 3.2 on 2024-04-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msme_app', '0004_auto_20240402_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='msmequestionnaire',
            name='groupreg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='msmequestionnaire',
            name='cboreg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='msmequestionnaire',
            name='disability',
            field=models.BooleanField(default=False),
        ),
    ]
