# Generated by Django 3.2 on 2024-04-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msme_app', '0005_auto_20240402_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msmequestionnaire',
            name='cboreg',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='msmequestionnaire',
            name='disability',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='msmequestionnaire',
            name='groupreg',
            field=models.CharField(max_length=100),
        ),
    ]
