# Generated by Django 3.2 on 2024-04-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msme_app', '0006_auto_20240403_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msmequestionnaire',
            name='cboreg',
        ),
        migrations.RemoveField(
            model_name='msmequestionnaire',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='msmequestionnaire',
            name='groupreg',
        ),
    ]
