# Generated by Django 3.2 on 2024-04-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msme_app', '0007_auto_20240403_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='msmequestionnaire',
            name='cboreg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='msmequestionnaire',
            name='disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='msmequestionnaire',
            name='groupreg',
            field=models.BooleanField(default=False),
        ),
    ]
