# Generated by Django 3.2 on 2024-04-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msme_app', '0008_auto_20240403_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msmequestionnaire',
            old_name='cboreg',
            new_name='chama',
        ),
        migrations.RenameField(
            model_name='msmequestionnaire',
            old_name='groupname',
            new_name='chamaOperation',
        ),
        migrations.RenameField(
            model_name='msmequestionnaire',
            old_name='groupreg',
            new_name='isChamaRegistered',
        ),
        migrations.RenameField(
            model_name='msmequestionnaire',
            old_name='groupoperationalyears',
            new_name='membershipPosition',
        ),
        migrations.RenameField(
            model_name='msmequestionnaire',
            old_name='position',
            new_name='nameOfChama',
        ),
        migrations.RenameField(
            model_name='msmequestionnaire',
            old_name='subcounty',
            new_name='subCounty',
        ),
    ]
