# Generated by Django 3.2 on 2024-04-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msme_app', '0010_alter_msmequestionnaire_chamaoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msmequestionnaire',
            name='chamaOperation',
            field=models.CharField(choices=[('0-1 year', '0-1 year'), ('1-2 years', '1-2 years'), ('Above 2 years', 'Above 2 years')], max_length=20),
        ),
    ]
